
services:
  - type: web
    name: united-hub-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production

  - type: worker
    name: united-hub-discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python discord_bot_example.py"
